version: "3.4"

services:
  ddfilm.api:
    container_name: ddfilm.app
    image: ${DOCKER_REGISTRY-}ddfilmapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=your_path
    build:
      context: .
      dockerfile: DDFilm.Api/Dockerfile
    ports:
      - "8084:8080"
      - "8085:8081"
    volumes:
      - your_path
    depends_on:
      - database.server
  database.server:
    container_name: database.server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "your_password"
    ports:
      - "1435:1433"
    volumes:
      - your_path
  seq.server:
    image: datalust/seq:latest
    container_name: seq.server
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  ddfilm.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
